### root.http is for the http server that is running on the server and helps to communicate with the server and the client
### CRUD is for create, read, update, delete
### fetch. data from the server
GET http://localhost:8000/api/v1/task/

### add task to the server
POST  http://localhost:8000/api/v1/task/
Content-Type: application/json

{
    "id": 2,
    "task": "Yubaraj",
    "hr":200
}

### root api 
GET   http://localhost:8000/

### update task 
PATCH http://localhost:8000/api/v1/task/
Content-Type: application/json

{
    "_id": "62ce08db358d079f6b36a9fa",
    "type": "bad"
}



### delete task 
DELETE http://localhost:8000/api/v1/task/
Content-Type: application/json

{
    "ids": ["62ce08dd358d079f6b36a9fc","62ce08dd358d079f6b36a9fe" ]
}

